Add secret files documentation
Azure/adx-automation-client pull request #25
Opened 2018-04-18 23:01 UTC by mcardosos

2018-04-18 23:16 UTC, troydai requested changes

2018-04-18 23:16 UTC, troydai commented on docs/onboard.md
> +Maybe your credentials are not environment variables but secret files. In this case, set them like this:
I will word it like this:
> To inject the credential as a file ....

2018-04-18 23:24 UTC, mcardosos commented on docs/onboard.md
> +Maybe your credentials are not environment variables but secret files. In this case, set them like this:
Done

2018-04-19 15:56 UTC, troydai approved these changes

2018-04-19 15:56 UTC, merged